const { generateTagFormatter } = require('../../libs/format_styled_components')

const EXPECTED_NAMES = {
  '(A|^a)rticle$': 'Article$',
  '(A|^a)side$': 'Aside$',
  '(B|^b)utton$': 'Button$',
  '(Date|Wareki)Picker$': '(Date|Wareki)Picker$',
  '(F|^f)ieldset$': 'Fieldset$',
  '(F|^f)orm$': 'Form$',
  '(Heading|^h(2|3|4|5|6))$': 'Heading$',
  '(I|^i)nput$': 'Input$',
  '(L|^l)abel$': 'Label$',
  '(N|^n)av$': 'Nav$',
  '(Ordered(.*)List|^ol)$': 'Ordered(.*)List$',
  '(PageHeading|^h1)$': 'PageHeading$',
  '(S|^s)ection$': 'Section$',
  '(S|^s)elect$': 'Select$',
  '(T|^t)extarea$': 'Textarea$',
  'AccordionPanel$': 'AccordionPanel$',
  'ActionDialogWithTrigger$': 'ActionDialogWithTrigger$',
  'Anchor$': 'Anchor$',
  'Base$': 'Base$',
  'BaseColumn$': 'BaseColumn$',
  'Center$': 'Center$',
  'Check(B|b)ox$': 'Checkbox$',
  'Check(B|b)ox(e)?s$': 'Checkboxes$',
  'Cluster$': 'Cluster$',
  'Combo(B|b)ox$': 'Combobox$',
  'DropZone$': 'DropZone$',
  'FieldSet$': 'FieldSet$',
  'Fieldsets$': 'Fieldsets$',
  'FilterDropdown$': 'FilterDropdown$',
  'FormControl$': 'FormControl$',
  'FormControls$': 'FormControls$',
  'FormDialog$': 'FormDialog$',
  'FormGroup$': 'FormGroup$',
  'Icon$': 'Icon$',
  'Image$': 'Image$',
  'Img$': 'Img$',
  'InputFile$': 'InputFile$',
  'Link$': 'Link$',
  'Message$': 'Message$',
  'ModelessDialog$': 'ModelessDialog$',
  'Pagination$': 'Pagination$',
  'RadioButton$': 'RadioButton$',
  'RadioButtonPanel$': 'RadioButtonPanel$',
  'RadioButtonPanels$': 'RadioButtonPanels$',
  'RadioButtons$': 'RadioButtons$',
  'Reel$': 'Reel$',
  'RemoteDialogTrigger$': 'RemoteDialogTrigger$',
  'RemoteTrigger(.*)FormDialog$': 'RemoteTrigger(.*)FormDialog$',
  'RemoteTrigger(.+)Dialog$': 'RemoteTrigger(.+)Dialog$',
  'RightFixedNote$': 'RightFixedNote$',
  'SearchInput$': 'SearchInput$',
  'SegmentedControl$': 'SegmentedControl$',
  'SideNav$': 'SideNav$',
  'Sidebar$': 'Sidebar$',
  'SmartHRLogo$': 'SmartHRLogo$',
  'Stack$': 'Stack$',
  'Switch$': 'Switch$',
  'TabItem$': 'TabItem$',
  'Text$': 'Text$',
  'TimePicker$': 'TimePicker$',
  '^(img|svg)$': '(Img|Image|Icon)$',
  '^a$': '(Anchor|Link)$',
}

const unexpectedMessageTemplate = `{{extended}} は smarthr-ui/{{expected}} をextendすることを期待する名称になっています
 - childrenにHeadingを含まない場合、コンポーネントの名称から"{{expected}}"を取り除いてください
 - childrenにHeadingを含み、アウトラインの範囲を指定するためのコンポーネントならば、smarthr-ui/{{expected}}をexendしてください
   - "styled(Xxxx)" 形式の場合、拡張元であるXxxxコンポーネントの名称の末尾に"{{expected}}"を設定し、そのコンポーネント内でsmarthr-ui/{{expected}}を利用してください`
const UNEXPECTED_NAMES = {
  '(Anchor|^a)$': '(Anchor)$',
  '(A|^a)rticle$': ['(Article)$', unexpectedMessageTemplate ],
  '(A|^a)side$': ['(Aside)$', unexpectedMessageTemplate ],
  '(B|^b)utton$': '(Button)$',
  '(Date|Wareki)Picker$': '((Date|Wareki)Picker)$',
  '(F|^f)ieldset$': '(Fieldset)$',
  '(F|^f)orm$': '(Form)$',
  '(Heading|^h(1|2|3|4|5|6))$': '(Heading)$',
  '(Icon|^(img|svg))$': '(Icon)$',
  '(Image|^(img|svg))$': '(Image)$',
  '(Img|^(img|svg))$': '(Img)$',
  '(I|^i)nput$': '(Input)$',
  '(Link|^a)$': '(Link)$',
  '(L|^l)abel$': '(Label)$',
  '(N|^n)av$': ['(Nav)$', unexpectedMessageTemplate ],
  '(Ordered(.*)List|^ol)$': '(Ordered(.*)List)$',
  '(S|^s)ection$': ['(Section)$', unexpectedMessageTemplate ],
  '(S|^s)elect$': '(Select)$',
  '(T|^t)extarea$': '(Textarea)$',
  'Base$': '(Base)$',
  'BaseColumn$': '(BaseColumn)$',
  'Center$': '(Center)$',
  'Check(B|b)ox$': '(Checkbox)$',
  'Check(B|b)ox(e)?s$': '(Checkboxes)$',
  'Cluster$': '(Cluster)$',
  'Combo(B|b)ox$': '(Combobox)$',
  'Fieldsets$': '(Fieldsets)$',
  'FilterDropdown$': '(FilterDropdown)$',
  'FormControl$': '(FormControl)$',
  'FormControls$': '(FormControls)$',
  'FormDialog$': '(FormDialog)$',
  'FormGroup$': '(FormGroup)$',
  'InputFile$': '(InputFile)$',
  'RadioButton$': '(RadioButton)$',
  'RadioButtonPanel$': '(RadioButtonPanel)$',
  'RadioButtonPanels$': '(RadioButtonPanels)$',
  'RadioButtons$': '(RadioButtons)$',
  'Reel$': '(Reel)$',
  'RemoteTrigger(.*)FormDialog$': '(RemoteTrigger(.*)FormDialog)$',
  'SearchInput$': '(SearchInput)$',
  'Sidebar$': '(Sidebar)$',
  'Stack$': '(Stack)$',
  'TimePicker$': '(TimePicker)$',
}


const SCHEMA = []

/**
 * @type {import('@typescript-eslint/utils').TSESLint.RuleModule<''>}
 */
module.exports = {
  meta: {
    type: 'problem',
    schema: SCHEMA,
  },
  create(context) {
    return generateTagFormatter({ context, EXPECTED_NAMES, UNEXPECTED_NAMES })
  },
}
module.exports.schema = SCHEMA
