/**
 * SmartHR 全社共通の oxlint 設定
 *
 * eslint-config-smarthr の oxlint 版。
 * プロダクト横断で共有するルールセットを定義する。
 *
 * NOTE: ESLint / oxlint 併用期間中は、ルールの追加・変更時に
 * eslint-config-smarthr (packages/eslint-config-smarthr/index.js) にも同じ修正を適用すること。
 *
 * @type {import('oxlint').OxlintConfig}
 */
const config = {
  plugins: ['typescript', 'import', 'react', 'jsx-a11y'],
  jsPlugins: ['eslint-plugin-smarthr'],
  env: {
    builtin: true,
    browser: true,
    commonjs: true,
    es2016: true,
  },
  rules: {

    // === ESLint recommended ===
    'constructor-super': 'error',
    'for-direction': 'error',
    'no-async-promise-executor': 'error',
    'no-case-declarations': 'error',
    'no-class-assign': 'error',
    'no-compare-neg-zero': 'error',
    'no-cond-assign': 'error',
    'no-const-assign': 'error',
    'no-constant-binary-expression': 'error',
    'no-constant-condition': 'error',
    'no-control-regex': 'error',
    'no-debugger': 'error',
    'no-delete-var': 'error',
    'no-dupe-class-members': 'error',
    'no-dupe-else-if': 'error',
    'no-dupe-keys': 'error',
    'no-duplicate-case': 'error',
    'no-empty': 'error',
    'no-empty-character-class': 'error',
    'no-empty-pattern': 'error',
    'no-empty-static-block': 'error',
    'no-ex-assign': 'error',
    'no-extra-boolean-cast': 'error',
    'no-fallthrough': 'error',
    'no-func-assign': 'error',
    'no-global-assign': 'error',
    'no-import-assign': 'error',
    'no-invalid-regexp': 'error',
    'no-irregular-whitespace': 'error',
    'no-loss-of-precision': 'error',
    'no-misleading-character-class': 'error',
    'no-new-native-nonconstructor': 'error',
    'no-nonoctal-decimal-escape': 'error',
    'no-obj-calls': 'error',
    'no-prototype-builtins': 'error',
    'no-redeclare': 'error',
    'no-regex-spaces': 'error',
    'no-self-assign': 'error',
    'no-setter-return': 'error',
    'no-shadow-restricted-names': 'error',
    'no-sparse-arrays': 'error',
    'no-this-before-super': 'error',
    'no-unsafe-finally': 'error',
    'no-unsafe-negation': 'error',
    'no-unsafe-optional-chaining': 'error',
    'no-unused-labels': 'error',
    'no-unused-private-class-members': 'error',
    'no-useless-backreference': 'error',
    'no-useless-catch': 'error',
    'no-useless-escape': 'error',
    'no-with': 'error',
    'require-yield': 'error',
    'use-isnan': 'error',
    'valid-typeof': ['error', { requireStringLiterals: true }],

    // === ESLint best practices ===
    'array-callback-return': 'warn',
    'block-scoped-var': 'warn',
    'default-param-last': 'error',
    eqeqeq: 'error',
    'import/no-duplicates': 'error',
    'no-caller': 'error',
    'no-div-regex': 'warn',
    'no-eval': 'error',
    'no-extend-native': 'error',
    'no-inner-declarations': 'warn',
    'no-iterator': 'error',
    'no-label-var': 'error',
    'no-lone-blocks': 'error',
    'no-loop-func': 'warn',
    'no-new-func': 'error',
    'no-new-wrappers': 'error',
    'no-proto': 'error',
    'no-return-assign': 'error',
    'no-script-url': 'warn',
    'no-self-compare': 'error',
    'no-sequences': 'error',
    'no-shadow': 'error',
    'no-throw-literal': 'error',
    'no-unmodified-loop-condition': 'warn',
    'no-unused-expressions': 'error',
    'no-useless-call': 'warn',
    'no-useless-computed-key': 'error',
    'no-useless-concat': 'error',
    'no-useless-rename': 'error',
    'no-var': 'error',
    'no-void': 'error',
    'prefer-const': ['warn', { destructuring: 'all', ignoreReadBeforeAssign: true }],
    'prefer-numeric-literals': 'error',
    'prefer-rest-params': 'error',
    'prefer-spread': 'warn',
    radix: 'error',
    'symbol-description': 'error',
    'vars-on-top': 'warn',
    'no-array-constructor': 'error',

    // === React recommended ===
    'react/jsx-key': 'error',
    'react/jsx-no-comment-textnodes': 'error',
    'react/jsx-no-duplicate-props': 'error',
    'react/jsx-no-target-blank': 'error',
    'react/jsx-no-undef': 'error',
    'react/no-children-prop': 'warn',
    'react/no-danger-with-children': 'error',
    'react/no-direct-mutation-state': 'error',
    'react/no-find-dom-node': 'error',
    'react/no-is-mounted': 'error',
    'react/no-render-return-value': 'error',
    'react/no-string-refs': 'error',
    'react/no-unescaped-entities': 'warn',
    'react/no-unknown-property': 'error',

    // === React hooks ===
    'react/exhaustive-deps': 'error',
    'react/rules-of-hooks': 'error',

    // === jsx-a11y ===
    'jsx-a11y/alt-text': 'warn',
    'jsx-a11y/anchor-has-content': 'warn',
    'jsx-a11y/aria-activedescendant-has-tabindex': 'warn',
    'jsx-a11y/aria-props': 'warn',
    'jsx-a11y/aria-role': 'warn',
    'jsx-a11y/aria-unsupported-elements': 'warn',
    'jsx-a11y/heading-has-content': 'warn',
    'jsx-a11y/html-has-lang': 'error',
    'jsx-a11y/iframe-has-title': 'warn',
    'jsx-a11y/label-has-associated-control': 'warn',
    'jsx-a11y/lang': 'error',
    'jsx-a11y/media-has-caption': 'warn',
    'jsx-a11y/mouse-events-have-key-events': 'warn',
    'jsx-a11y/no-access-key': 'warn',
    'jsx-a11y/no-autofocus': 'warn',
    'jsx-a11y/no-distracting-elements': 'warn',
    'jsx-a11y/no-noninteractive-tabindex': 'warn',
    'jsx-a11y/no-redundant-roles': 'warn',
    'jsx-a11y/role-has-required-aria-props': 'warn',
    'jsx-a11y/role-supports-aria-props': 'warn',
    'jsx-a11y/scope': 'warn',
    'jsx-a11y/tabindex-no-positive': 'warn',

    // === React additional rules ===
    'react/jsx-curly-brace-presence': 'error',
    'react/jsx-filename-extension': ['error', { extensions: ['.tsx', '.jsx'] }],
    'react/jsx-fragments': ['error', 'syntax'],
    'react/jsx-no-useless-fragment': 'error',
    'react/jsx-pascal-case': ['warn', { allowAllCaps: true }],
    'react/no-did-mount-set-state': 'error',
    'react/no-redundant-should-component-update': 'error',
    'react/no-this-in-sfc': 'error',
    'react/no-will-update-set-state': 'error',
    'react/prefer-es6-class': 'error',
    'react/style-prop-object': 'error',
    'react/void-dom-elements-no-children': 'error',

    // === TypeScript ===
    'typescript/dot-notation': 'error',
    'typescript/no-duplicate-enum-values': 'error',
    'typescript/no-empty-object-type': 'error',
    'typescript/no-extra-non-null-assertion': 'error',
    'typescript/no-misused-new': 'error',
    'typescript/no-namespace': 'error',
    'typescript/no-non-null-asserted-optional-chain': 'error',
    'typescript/no-require-imports': 'error',
    'typescript/no-this-alias': 'error',
    'typescript/no-unnecessary-type-constraint': 'error',
    'typescript/no-unsafe-declaration-merging': 'error',
    'typescript/no-unsafe-function-type': 'error',
    'typescript/no-wrapper-object-types': 'error',
    'typescript/prefer-as-const': 'error',
    'typescript/triple-slash-reference': 'error',
    'typescript/array-type': ['error', { default: 'array-simple' }],
    'typescript/unified-signatures': 'warn',
    'typescript/consistent-type-imports': ['error', { fixStyle: 'inline-type-imports' }],
    'typescript/no-import-type-side-effects': 'error',

    // === eslint-plugin-smarthr ===
    'eslint-plugin-smarthr/a11y-anchor-has-href-attribute': 'error',
    'eslint-plugin-smarthr/a11y-aria-labelledby': 'warn',
    'eslint-plugin-smarthr/a11y-clickable-element-has-text': 'error',
    'eslint-plugin-smarthr/a11y-form-control-in-form': 'error',
    'eslint-plugin-smarthr/a11y-heading-in-sectioning-content': 'error',
    'eslint-plugin-smarthr/a11y-help-link-with-support-href': 'error',
    'eslint-plugin-smarthr/a11y-image-has-alt-attribute': 'error',
    'eslint-plugin-smarthr/a11y-input-has-name-attribute': 'error',
    'eslint-plugin-smarthr/a11y-input-in-form-control': 'error',
    'eslint-plugin-smarthr/a11y-numbered-text-within-ol': 'error',
    'eslint-plugin-smarthr/a11y-prohibit-checkbox-or-radio-in-table-cell': 'error',
    'eslint-plugin-smarthr/a11y-prohibit-input-maxlength-attribute': 'error',
    'eslint-plugin-smarthr/a11y-prohibit-input-placeholder': 'error',
    'eslint-plugin-smarthr/a11y-prohibit-overflow-hidden': 'warn',
    'eslint-plugin-smarthr/a11y-prohibit-sectioning-content-in-form': 'error',
    'eslint-plugin-smarthr/a11y-prohibit-useless-sectioning-fragment': 'error',
    'eslint-plugin-smarthr/a11y-scroller-has-tabindex': 'warn',
    'eslint-plugin-smarthr/a11y-trigger-has-button': 'error',
    'eslint-plugin-smarthr/best-practice-for-async-current-target': 'error',
    'eslint-plugin-smarthr/best-practice-for-button-element': 'error',
    'eslint-plugin-smarthr/best-practice-for-date': 'error',
    'eslint-plugin-smarthr/best-practice-for-data-test-attribute': 'off',
    'eslint-plugin-smarthr/best-practice-for-interactive-element': 'error',
    'eslint-plugin-smarthr/best-practice-for-layouts': 'error',
    'eslint-plugin-smarthr/best-practice-for-nested-attributes-array-index': 'error',
    'eslint-plugin-smarthr/best-practice-for-optional-chaining': 'error',
    'eslint-plugin-smarthr/best-practice-for-prohibit-import-smarthr-ui-local': 'error',
    'eslint-plugin-smarthr/best-practice-for-remote-trigger-dialog': 'error',
    'eslint-plugin-smarthr/best-practice-for-rest-parameters': 'off',
    'eslint-plugin-smarthr/best-practice-for-spread-syntax': ['error', { fix: true }],
    'eslint-plugin-smarthr/best-practice-for-tailwind-prohibit-root-margin': 'off',
    'eslint-plugin-smarthr/best-practice-for-tailwind-variants': 'off',
    'eslint-plugin-smarthr/best-practice-for-text-component': 'warn',
    'eslint-plugin-smarthr/best-practice-for-unnesessary-early-return': 'off',
    'eslint-plugin-smarthr/component-name': 'error',
    'eslint-plugin-smarthr/design-system-guideline-prohibit-dialog-button-icon': 'warn',
    'eslint-plugin-smarthr/design-system-guideline-prohibit-double-icons': 'off',
    'eslint-plugin-smarthr/format-import-path': 'off',
    'eslint-plugin-smarthr/format-translate-component': 'off',
    'eslint-plugin-smarthr/no-import-other-domain': 'off',
    'eslint-plugin-smarthr/prohibit-export-array-type': 'error',
    'eslint-plugin-smarthr/prohibit-file-name': 'off',
    'eslint-plugin-smarthr/prohibit-import': 'off',
    'eslint-plugin-smarthr/prohibit-path-within-template-literal': 'off',
    'eslint-plugin-smarthr/require-barrel-import': 'error',
    'eslint-plugin-smarthr/require-declaration': 'off',
    'eslint-plugin-smarthr/require-export': 'off',
    'eslint-plugin-smarthr/require-i18n-text': 'warn',
    'eslint-plugin-smarthr/require-import': 'off',
    'eslint-plugin-smarthr/trim-props': 'error',
  },
}

export default config
