name: debugUnknownDiff

on:
  push:
    branches:
      - "chore/debug-unknown-diff"
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v6
        with:
          package_json_file: 'package.json'
          run_install: false
      - uses: actions/setup-node@v6
        with:
          node-version-file: '.node-version'
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'
      - run: pnpm install
      - run: pnpm release
