name: lint

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build:
    name: Node.js ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Use Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version-file: '.node-version'
      - name: pnpm install, and pnpm lint
        run: |
          corepack enable && corepack prepare --activate
          pnpm install
          pnpm lint
        env:
          CI: true
